"""reviews depth + product Q&A

Revision ID: 244577678664
Revises: 7a598dc14167
Create Date: 2026-06-18 01:39:31.794984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '244577678664'
down_revision: Union[str, Sequence[str], None] = '7a598dc14167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_questions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_questions_product_id'), ['product_id'], unique=False)

    op.create_table('product_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_staff_answer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['product_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_answers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_answers_question_id'), ['question_id'], unique=False)

    op.create_table('review_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'review_id', name='uq_reviewvote_user_review')
    )
    with op.batch_alter_table('review_votes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_votes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_votes_review_id'), ['review_id'], unique=False)

    # (variant_id FKs are intentionally app-enforced, not added at the DB level.)
    op.add_column('reviews', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('status', sa.String(), nullable=False, server_default='approved'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'status')
    op.drop_column('reviews', 'image_url')

    with op.batch_alter_table('review_votes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_votes_review_id'))
        batch_op.drop_index(batch_op.f('ix_review_votes_id'))

    op.drop_table('review_votes')
    with op.batch_alter_table('product_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_product_answers_id'))

    op.drop_table('product_answers')
    with op.batch_alter_table('product_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_questions_product_id'))
        batch_op.drop_index(batch_op.f('ix_product_questions_id'))

    op.drop_table('product_questions')
    # ### end Alembic commands ###
