"""discovery: recently_viewed, back_in_stock, saved_payment_methods

Revision ID: 24f2dc0f18d6
Revises: 43f1fc048308
Create Date: 2026-06-18 01:00:16.934935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24f2dc0f18d6'
down_revision: Union[str, Sequence[str], None] = '43f1fc048308'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('back_in_stock_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_bis_user_product')
    )
    with op.batch_alter_table('back_in_stock_subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_back_in_stock_subscriptions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_back_in_stock_subscriptions_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_back_in_stock_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('recently_viewed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_recent_user_product')
    )
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recently_viewed_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recently_viewed_user_id'), ['user_id'], unique=False)

    op.create_table('saved_payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('method_type', sa.String(), nullable=False),
    sa.Column('last4', sa.String(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saved_payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_payment_methods_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_payment_methods_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_payment_methods_user_id'))
        batch_op.drop_index(batch_op.f('ix_saved_payment_methods_id'))

    op.drop_table('saved_payment_methods')
    with op.batch_alter_table('recently_viewed', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recently_viewed_user_id'))
        batch_op.drop_index(batch_op.f('ix_recently_viewed_id'))

    op.drop_table('recently_viewed')
    with op.batch_alter_table('back_in_stock_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_back_in_stock_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_back_in_stock_subscriptions_product_id'))
        batch_op.drop_index(batch_op.f('ix_back_in_stock_subscriptions_id'))

    op.drop_table('back_in_stock_subscriptions')
    # ### end Alembic commands ###
