"""wallet, gift cards, referral

Revision ID: 5c4ed6044324
Revises: 244577678664
Create Date: 2026-06-18 01:46:19.220428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c4ed6044324'
down_revision: Union[str, Sequence[str], None] = '244577678664'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('purchaser_id', sa.Integer(), nullable=True),
    sa.Column('recipient_email', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['purchaser_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gift_cards_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_gift_cards_id'), ['id'], unique=False)

    op.create_table('wallet_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_wallet_transactions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_wallet_transactions_user_id'), ['user_id'], unique=False)

    # (variant_id FKs intentionally app-enforced; referred_by_id FK likewise.)
    op.add_column('users', sa.Column('referral_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('referred_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_column('users', 'referred_by_id')
    op.drop_column('users', 'referral_code')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('wallet_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_user_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_id'))
        batch_op.drop_index(batch_op.f('ix_wallet_transactions_created_at'))

    op.drop_table('wallet_transactions')
    with op.batch_alter_table('gift_cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gift_cards_id'))
        batch_op.drop_index(batch_op.f('ix_gift_cards_code'))

    op.drop_table('gift_cards')
    # ### end Alembic commands ###
